import Head from 'next/head'
import Link from 'next/link'
import styles from '../../styles/Home.module.css'
import { useEffect } from 'react'
import socketIOClient from 'socket.io-client'

const Character = () => {
    useEffect(() => {
        console.log("yoo")
        const socket = socketIOClient('localhost:3001');
        socket.on('connect', (data) => {
            console.log('client connected successfully!')
        })
    },[]);

    return (
        <div className={styles.container}>
            <Head>
                <title>DnD Character Sheet</title>
                <meta name="Customized dnd character sheet" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.charMain}>
                <div className={styles.wrapper}>
                    <div className={`${styles.box} ${styles.charName}`}>character name</div>
                    <div className={`${styles.box} ${styles.charSaves}`}>character health/AC</div>
                    <div className={`${styles.box} ${styles.charHealth}`}>character saves</div>
                    <div className={`${styles.box} ${styles.chatBox}`}>chat box</div>
                    <div className={`${styles.box} ${styles.charActions}`}>character actions</div>
                </div>
            </main>

            <footer>
                <Link href="/">
                    <a>go home</a>
                </Link>
            </footer>
        </div>
    );
}

export default Character;