import Head from 'next/head'
import Link from 'next/link'
import styles from '../../styles/Home.module.css'
import { useEffect, useState } from 'react'
import socketIOClient from 'socket.io-client'
import { rollDice } from '../../util/roll'
import { CharacterModel } from '../../util/characterModel'
import { getCharacter, getCharacterNames, saveCharacter } from '../../util/storage'

const Character = () => {
    const [socket, setSocket] = useState(null);
    const [messages, setMessages] = useState([]);
    const [name, setName] = useState(''); // not sure wanna use input since im not actually submiting to a backend
    const [characterModel, setCharacterModel] = useState({class: "foo"});

    useEffect(() => {
        console.log("yoo")
        const socket = socketIOClient('localhost:3001');
        setSocket(socket)
        socket.on('connect', (data) => {
            console.log('client connected successfully!')
        })
        socket.on('message',(msg) => {
            setMessages( msgs => [...msgs, msg])
        })
    },[setSocket]);

    const handleRoll = () => {
        const randomNumber = Math.floor(Math.random() * 6) + 1;
        socket.emit('message', `${name} rolled a ${randomNumber}!`)
    }

    // curry function
    const handleChange = prop => (e) => {
        let updatedVal = {}
        updatedVal[prop] = e.target.value
        setCharacterModel(model => ({
            ...characterModel,
            ...updatedVal
        }))
    }

    return (
        <div className="container mx-auto mt-4 max-w-7xl">
            <Head>
                <title>DnD Character Sheet</title>
                <meta name="Customized dnd character sheet" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div id="actionBar" className="flex flex-row flex-nowrap justify-start">
                <button className="text-white bg-blue-700 hover:bg-blue-800 rounded-lg px-5 py-2.5 mr-2 mb-2">Save Changes</button>
                <button className="text-white bg-blue-700 hover:bg-blue-800 rounded-lg px-5 py-2.5 mr-2 mb-2" data-modal-toggle="loadModal">Load</button>
                <button className="text-white bg-blue-700 hover:bg-blue-800 rounded-lg px-5 py-2.5 mr-2 mb-2" data-modal-toggle="loginModal">Login</button>
                <button className="text-white bg-blue-700 hover:bg-blue-800 rounded-lg px-5 py-2.5 mr-2 mb-2"><a href="./">Home</a></button>
            </div>
            {JSON.stringify(characterModel)}

            <div id="loginModal" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 w-full md:inset-0 h-modal md:h-full">
                <div class="relative p-4 w-full max-w-2xl h-full md:h-auto">
                    <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
                        <div class="flex justify-between items-start p-4 rounded-t border-b dark:border-gray-600">
                            <h3 class="text-xl font-semibold text-gray-900 dark:text-white">
                                Login Integration
                            </h3>
                        </div>
                        <div class="p-6 space-y-6">
                            <p class="text-base leading-relaxed text-gray-500 dark:text-gray-400">
                                Discord
                            </p>
                        </div>
                        <div class="flex items-center p-6 space-x-2 rounded-b border-t border-gray-200 dark:border-gray-600">
                            <button data-modal-toggle="loginModal" type="button" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Close</button>
                        </div>
                    </div>
                </div>
            </div>
            <div id="loadModal" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 w-full md:inset-0 h-modal md:h-full">
                <div class="relative p-4 w-full max-w-2xl h-full md:h-auto">
                    <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
                        <div class="flex justify-between items-start p-4 rounded-t border-b dark:border-gray-600">
                            <h3 class="text-xl font-semibold text-gray-900 dark:text-white">
                                Load Character
                            </h3>
                        </div>
                        <div class="p-6 space-y-6">
                            <p class="text-base leading-relaxed text-gray-500 dark:text-gray-400">
                                Character
                            </p>
                        </div>
                        <div class="flex items-center p-6 space-x-2 rounded-b border-t border-gray-200 dark:border-gray-600">
                            <button data-modal-toggle="loadModal" type="button" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Close</button>
                        </div>
                    </div>
                </div>
            </div>

            <div className="mb-6">
                <label id="default-input" className="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Character Name</label>
                <input type="text" id="default-input" className="bg-gray-50 border border-gray-300 text-gray-900 text-lg font-bold rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Character Name" />
            </div>


            <div id="TabArea">
                <ul className="flex flex-wrap text-sm font-medium text-center text-gray-500 border-b border-blue-700 dark:border-gray-700 dark:text-gray-400" id="toptabs" data-tabs-toggle="#tabContent" role="tablist">
                    <li className="mr-8" role="presentation">
                        <button className="inline-block p-4 border-solid rounded-t-lg border-blue-700 border-t border-x hover:underline hover:border-blue-700" id="stats-tab" data-tabs-target="#stats" type="button" role="tab" aria-controls="stats" aria-selected="true">Stats &amp; Abilities</button>
                    </li>
                    <li className="mr-8" role="presentation">
                        <button className="inline-block p-4 border-solid rounded-t-lg border-blue-700 border-t border-x hover:underline hover:border-blue-700" id="notes-tab" data-tabs-target="#notes" type="button" role="tab" aria-controls="notes" aria-selected="false">Notes, Personality, etc</button>
                    </li>
                </ul>
            </div>

            <div id="tabContent">
                <div className="mt-4" id="stats" role="tabpanel" aria-labelledby='stats-tab'>
                    <div className="grid grid-cols-3 gap-x-8 gap-y-8">

                        <div id="basicInfo" className="col-span-3 col-end-auto">
                            <div className="flex justify-start flex-wrap flex-row items-center">
                            <dl className="flex flex-row justify-start items-center mb-4 mr-6 mt-2">
                                <dt>
                                    <label className="mb-2 text-sm font-medium text-gray-900">Class</label>
                                </dt>
                                <dd className="ml-8">
                                    <input type="text" id="dndclass" value={characterModel.class} onChange={handleChange("class")} className="px-2 py-1 bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500" />
                                </dd>
                            </dl>
                            <dl className="flex flex-row justify-start items-center mb-4 mr-6 mt-2">
                                <dt>
                                    <label className="mb-2 text-sm font-medium text-gray-900">Race</label>
                                </dt>
                                <dd className="ml-8">
                                    <input type="text" id="dndrace" value={characterModel.race} className="px-2 py-1 bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500" />
                                </dd>
                            </dl>
                            <dl className="flex flex-row justify-start items-center mb-4 mr-6 mt-2">
                                <dt>
                                    <label className="mb-2 text-sm font-medium text-gray-900">Background</label>
                                </dt>
                                <dd className="ml-8">
                                    <input type="text" id="dndbackground" value={characterModel.background} className="px-2 py-1 bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500" />
                                </dd>
                            </dl>
                            <dl className="flex flex-row justify-start items-center mb-4 mr-6 mt-2">
                                <dt>
                                    <label className="mb-2 text-sm font-medium text-gray-900">Alignment</label>
                                </dt>
                                <dd className="ml-8">
                                    <input type="text" id="dndalignment" value={characterModel.alignment} className="px-2 py-1 bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500" />
                                </dd>
                            </dl>
                            <dl className="flex flex-row justify-start items-center mb-4 mr-6 mt-2">
                                <dt>
                                    <label className="mb-2 text-sm font-medium text-gray-900">Level</label>
                                </dt>
                                <dd className="ml-8">
                                    <input type="text" id="dndlevel" size="1" className="px-2 py-1 bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500" />
                                </dd>
                            </dl>
                            <dl className="flex flex-row justify-start items-center mb-4 mr-6 mt-2">
                                <dt>
                                    <label className="mb-2 text-sm font-medium text-gray-900">Experience</label>
                                </dt>
                                <dd className="ml-8">
                                    <input type="text" id="dndexp" size="2" className="px-2 py-1 bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500" />
                                </dd>
                            </dl>
                            <dl className="flex flex-row justify-start items-center mb-4 mr-6 mt-2">
                                <dt>
                                    <label className="mb-2 text-sm font-medium text-gray-900">Speed</label>
                                </dt>
                                <dd className="ml-8">
                                    <input type="text" id="dndspeed" size="2" className="px-2 py-1 bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500" />
                                </dd>
                            </dl>
                            <dl className="flex flex-row justify-start items-center mb-4 mr-6 mt-2">
                                <dt>
                                    <label className="mb-2 text-sm font-medium text-gray-900">Initiative</label>
                                </dt>
                                <dd className="ml-8">
                                    <input type="text" id="dndinitiative" size="2" className="px-2 py-1 bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500" />
                                </dd>
                            </dl>
                            <dl className="flex flex-row justify-start items-center mb-4 mr-6 mt-2">
                                <dt>
                                    <label className="mb-2 text-sm font-medium text-gray-900">Armor Class</label>
                                </dt>
                                <dd className="ml-8">
                                    <input type="text" id="dndac" size="2" className="px-2 py-1 bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500" />
                                </dd>
                            </dl>
                            <dl className="flex flex-row justify-start items-center mb-4 mr-6 mt-2">
                                <dt>
                                    <label className="mb-2 text-sm font-medium text-gray-900">Hit Points</label>
                                </dt>
                                <dd className="ml-8">
                                    <input type="text" id="dndhp" size="4" className="px-2 py-1 bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500" />
                                </dd>
                            </dl>
                            <dl className="flex flex-row justify-start items-center mb-4 mr-6 mt-2">
                                <dt>
                                    <label className="mb-2 text-sm font-medium text-gray-900">Temporary HP</label>
                                </dt>
                                <dd className="ml-8">
                                    <input type="text" id="dndtemphp" size="2" className="px-2 py-1 bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500" />
                                </dd>
                            </dl>
                            <dl className="flex flex-row justify-start items-center mb-4 mr-6 mt-2">
                                <dt>
                                    <label className="mb-2 text-sm font-medium text-gray-900">Proficiency Bonus</label>
                                </dt>
                                <dd className="ml-8">
                                    +0
                                </dd>
                            </dl>
                            </div>
                        </div>

                        <div id="skillsAttributes" className="col-span-1 border-solid rounded-md border-gray-600 border p-2">
                            <h2 className="text-base font-bold mb-4">Attributes</h2>
                            <div>
                                {/* this will be a for loop attribute rendering state */}
                                <div className="mb-2">
                                    <label className="mr-6 text-sm font-bold">Str</label>
                                    <input type="number" max={20} min={3} className="text-xs mr-4 w-12 border-dotted border rounded-md px-2 py-1" />
                                    <span className="mr-4">0</span>
                                    <input type="checkbox" className="mr-4 rounded-sm" />
                                    <label className="mr-4 text-sm font-bold">Save</label>
                                    <span className="mr-4">0</span>
                                    <input type="image" src="d20-32px.svg" className="mr-4 inline-block object-contain align-middle" height={20} />
                                </div>
                                <div className="mb-2">
                                    <label className="mr-4 text-sm font-bold">Dex</label>
                                    <input type="number" max={20} min={3} className="text-xs mr-4 w-12 border-dotted border rounded-md px-2 py-1" />
                                    <span className="mr-4">0</span>
                                    <input type="checkbox" className="mr-4 rounded-sm" />
                                    <label className="mr-4 text-sm font-bold">Save</label>
                                    <span className="mr-4">0</span>
                                    <input type="image" src="d20-32px.svg" className="mr-4 inline-block object-contain align-middle" height={20} />
                                </div>
                                <div className="mb-2">
                                    <label className="mr-4 text-sm font-bold">Con</label>
                                    <input type="number" max={20} min={3} className="text-xs mr-4 w-12 border-dotted border rounded-md px-2 py-1" />
                                    <span className="mr-4">0</span>
                                    <input type="checkbox" className="mr-4 rounded-sm" />
                                    <label className="mr-4 text-sm font-bold">Save</label>
                                    <span className="mr-4">0</span>
                                    <input type="image" src="d20-32px.svg" className="mr-4 inline-block object-contain align-middle" height={20} />
                                </div>
                                <div className="mb-2">
                                    <label className="mr-6 text-sm font-bold">Int</label>
                                    <input type="number" max={20} min={3} className="text-xs mr-4 w-12 border-dotted border rounded-md px-2 py-1" />
                                    <span className="mr-4">0</span>
                                    <input type="checkbox" className="mr-4 rounded-sm" />
                                    <label className="mr-4 text-sm font-bold">Save</label>
                                    <span className="mr-4">0</span>
                                    <input type="image" src="d20-32px.svg" className="mr-4 inline-block object-contain align-middle" height={20} />
                                </div>
                                <div className="mb-2">
                                    <label className="mr-4 text-sm font-bold">Wis</label>
                                    <input type="number" max={20} min={3} className="text-xs mr-4 w-12 border-dotted border rounded-md px-2 py-1" />
                                    <span className="mr-4">0</span>
                                    <input type="checkbox" className="mr-4 rounded-sm" />
                                    <label className="mr-4 text-sm font-bold">Save</label>
                                    <span className="mr-4">0</span>
                                    <input type="image" src="d20-32px.svg" className="mr-4 inline-block object-contain align-middle" height={20} />
                                </div>
                                <div className="mb-2">
                                    <label className="mr-4 text-sm font-bold">Cha</label>
                                    <input type="number" max={20} min={3} className="text-xs mr-4 w-12 border-dotted border rounded-md px-2 py-1" />
                                    <span className="mr-4">0</span>
                                    <input type="checkbox" className="mr-4 rounded-sm" />
                                    <label className="mr-4 text-sm font-bold">Save</label>
                                    <span className="mr-4">0</span>
                                    <input type="image" src="d20-32px.svg" className="mr-4 inline-block object-contain align-middle" height={20} />
                                </div>
                            </div>
                            <h2 className="text-base font-bold mb-4 mt-4">Skills</h2>
                            <div>
                                {/* this will be a for loop on the skill rendering */}
                                <div className="mb-2">
                                    <label>
                                        <input type="checkbox" className="mr-4 rounded-sm text-sm" />
                                        <input type="checkbox" className="mr-4 rounded-sm text-sm text-gray-400" disabled={true} />
                                    </label>
                                    <span className="mr-4 text-sm">Acrobatics (Dex)</span>
                                    <span className="mr-4">0</span>
                                    <input type="image" src="d20-32px.svg" className="mr-4 inline-block object-contain align-middle" height={20} />
                                </div>
                                <div className="mb-2">
                                    <label>
                                        <input type="checkbox" className="mr-4 rounded-sm text-sm" />
                                        <input type="checkbox" className="mr-4 rounded-sm text-sm text-gray-400" disabled={true} />
                                    </label>
                                    <span className="mr-4 text-sm">Animal Handling (Wis)</span>
                                    <span className="mr-4">0</span>
                                    <input type="image" src="d20-32px.svg" className="mr-4 inline-block object-contain align-middle" height={20} />
                                </div>
                            </div>
                        </div>

                        {/* dice roll regex https://regexr.com/3d70r */}
                        {/* https://www.npmjs.com/package/dice-notation-js */}
                        <div id="weaponAttacks" className="col-span-2 col-start-2 border-solid rounded-md border-gray-600 border p-2">
                            <h2 className="text-base font-bold mb-4">Weapons &amp; Attacks</h2>
                            <div className="grid grid-cols-6 gap-2">
                                <p className="font-bold">Name</p>
                                <p className="font-bold">Att Bonus</p>
                                <p className="font-bold">Damage</p>
                                <p className="font-bold">Type/Notes</p>
                                <p className="font-bold">Roll</p>
                                <p></p>

                                {/* should be dynamically generated */}
                                <input className="text-xs px-2 py-1 border border-solid border-gray-600 rounded-sm" />
                                <input type="number" className="text-xs px-2 py-1" min={-10} max={10} />
                                <input pattern="(\d+)?d(\d+)([\+\-]\d+)?" className="text-xs px-2 py-1 border border-solid border-gray-600 rounded-sm" />
                                <input className="text-xs px-2 py-1 border border-solid border-gray-600 rounded-sm" />
                                <input type="image" src="d20-32px.svg" className="mr-4 inline-block object-contain align-middle" height={20} />
                                <span />
                            </div>
                            <button className="rounded-md border border-solid border-gray-600 p-1 mt-2">New att</button>
                        </div>

                        <div id="spells" className="col-span-3 border-solid rounded-md border-gray-600 border p-2">
                            <p>extra</p>
                        </div>

                    </div>
                </div>

                <div className="mt-4" id="notes" role="tabpanel" aria-labelledby='notes-tab'>
                    <p>notes stuff</p>
                </div>
            </div>

            <script src="https://unpkg.com/flowbite@1.5.2/dist/flowbite.js"></script>
        </div>
    );
}

export default Character;