import Head from 'next/head'
import Link from 'next/link'
import styles from '../../styles/Home.module.css'
import { useEffect, useState } from 'react'
import socketIOClient from 'socket.io-client'
import { rollDice } from '../util/roll'

const Character = () => {
    const [socket, setSocket] = useState(null);
    const [messages, setMessages] = useState([]);
    const [name, setName] = useState(''); // not sure wanna use input since im not actually submiting to a backend

    useEffect(() => {
        console.log("yoo")
        const socket = socketIOClient('localhost:3001');
        setSocket(socket)
        socket.on('connect', (data) => {
            console.log('client connected successfully!')
        })
        socket.on('message',(msg) => {
            setMessages( msgs => [...msgs, msg])
        })
    },[setSocket]);

    const handleRoll = () => {
        const randomNumber = Math.floor(Math.random() * 6) + 1;
        socket.emit('message', `${name} rolled a ${randomNumber}!`)
    }

    const handleNameChange = (e) => {
        setName(e.target.value)
    }

    return (
        <div className="container mx-auto mt-4">
            <Head>
                <title>DnD Character Sheet</title>
                <meta name="Customized dnd character sheet" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div id="actionBar" className="flex flex-row flex-nowrap justify-start">
                <button className="text-white bg-blue-700 hover:bg-blue-800 rounded-lg px-5 py-2.5 mr-2 mb-2">Save Changes</button>
                <button className="text-white bg-blue-700 hover:bg-blue-800 rounded-lg px-5 py-2.5 mr-2 mb-2">Load</button>
                <button className="text-white bg-blue-700 hover:bg-blue-800 rounded-lg px-5 py-2.5 mr-2 mb-2">Login</button>
                <button className="text-white bg-blue-700 hover:bg-blue-800 rounded-lg px-5 py-2.5 mr-2 mb-2"><Link href="/">Home</Link></button>
            </div>

            <div className="mb-6">
                <label id="default-input" className="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Character Name</label>
                <input type="text" id="default-input" className="bg-gray-50 border border-gray-300 text-gray-900 text-lg font-bold rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Character Name" />
            </div>


<div className="mb-4 border-b border-gray-200 dark:border-gray-700">
    <ul className="flex flex-wrap -mb-px text-sm font-medium text-center" id="myTab" data-tabs-toggle="#myTabContent" role="tablist">
        <li className="mr-2" role="presentation">
            <button className="inline-block p-4 rounded-t-lg border-b-2 text-blue-600 hover:text-blue-600 dark:text-blue-500 dark:hover:text-blue-500 border-blue-600 dark:border-blue-500" id="profile-tab" data-tabs-target="#profile" type="button" role="tab" aria-controls="profile" aria-selected="true">Profile</button>
        </li>
        <li className="mr-2" role="presentation">
            <button className="inline-block p-4 rounded-t-lg border-b-2 border-transparent hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300 dark:border-transparent text-gray-500 dark:text-gray-400 border-gray-100 dark:border-gray-700" id="dashboard-tab" data-tabs-target="#dashboard" type="button" role="tab" aria-controls="dashboard" aria-selected="false">Dashboard</button>
        </li>
        <li className="mr-2" role="presentation">
            <button className="inline-block p-4 rounded-t-lg border-b-2 border-transparent hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300 dark:border-transparent text-gray-500 dark:text-gray-400 border-gray-100 dark:border-gray-700" id="settings-tab" data-tabs-target="#settings" type="button" role="tab" aria-controls="settings" aria-selected="false">Settings</button>
        </li>
        <li role="presentation">
            <button className="inline-block p-4 rounded-t-lg border-b-2 border-transparent hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300 dark:border-transparent text-gray-500 dark:text-gray-400 border-gray-100 dark:border-gray-700" id="contacts-tab" data-tabs-target="#contacts" type="button" role="tab" aria-controls="contacts" aria-selected="false">Contacts</button>
        </li>
    </ul>
</div>
<div id="myTabContent">
    <div className="p-4 bg-gray-50 rounded-lg dark:bg-gray-800" id="profile" role="tabpanel" aria-labelledby="profile-tab">
        <p className="text-sm text-gray-500 dark:text-gray-400">This is some placeholder content the <strong className="font-medium text-gray-800 dark:text-white">Profile tab's associated content</strong>. Clicking another tab will toggle the visibility of this one for the next. The tab JavaScript swaps classes to control the content visibility and styling.</p>
    </div>
    <div className="hidden p-4 bg-gray-50 rounded-lg dark:bg-gray-800" id="dashboard" role="tabpanel" aria-labelledby="dashboard-tab">
        <p className="text-sm text-gray-500 dark:text-gray-400">This is some placeholder content the <strong className="font-medium text-gray-800 dark:text-white">Dashboard tab's associated content</strong>. Clicking another tab will toggle the visibility of this one for the next. The tab JavaScript swaps classes to control the content visibility and styling.</p>
    </div>
    <div className="hidden p-4 bg-gray-50 rounded-lg dark:bg-gray-800" id="settings" role="tabpanel" aria-labelledby="settings-tab">
        <p className="text-sm text-gray-500 dark:text-gray-400">This is some placeholder content the <strong className="font-medium text-gray-800 dark:text-white">Settings tab's associated content</strong>. Clicking another tab will toggle the visibility of this one for the next. The tab JavaScript swaps classes to control the content visibility and styling.</p>
    </div>
    <div className="hidden p-4 bg-gray-50 rounded-lg dark:bg-gray-800" id="contacts" role="tabpanel" aria-labelledby="contacts-tab">
        <p className="text-sm text-gray-500 dark:text-gray-400">This is some placeholder content the <strong className="font-medium text-gray-800 dark:text-white">Contacts tab's associated content</strong>. Clicking another tab will toggle the visibility of this one for the next. The tab JavaScript swaps classes to control the content visibility and styling.</p>
    </div>
</div>

        <script src="https://unpkg.com/flowbite@1.5.2/dist/flowbite.js"></script>
        </div>


        // <div className={styles.container}>
        //     <Head>
        //         <title>DnD Character Sheet</title>
        //         <meta name="Customized dnd character sheet" content="Generated by create next app" />
        //         <link rel="icon" href="/favicon.ico" />
        //     </Head>

        //     <main className={styles.charMain}>
        //         <div className={styles.wrapper}>
        //             <div className={`${styles.box} ${styles.charName}`}>
        //                 character name
        //                 <label>Name</label>
        //                 <input type="text" id="name" name="name" onChange={handleNameChange} />
        //             </div>
        //             <div className={`${styles.box} ${styles.charSaves}`}>character health/AC</div>
        //             <div className={`${styles.box} ${styles.charHealth}`}>character saves</div>
        //             <div className={`${styles.box} ${styles.chatBox}`}>
        //                 chat box
        //                 <ul>
        //                     {messages.map((msg) => {
        //                         return(
        //                             <li>{msg}</li>
        //                         )
        //                     })}
        //                 </ul>
        //             </div>
        //             <div className={`${styles.box} ${styles.charActions}`}>
        //                 character actions
        //                 <button onClick={handleRoll}>click to roll</button>
        //             </div>
        //         </div>
        //     </main>

        //     <footer>
        //         <Link href="/">
        //             <a>go home</a>
        //         </Link>
        //     </footer>
        // </div>
    );
}

export default Character;